import os

PROJECT_NAME = "NAKSHATRA AI"
VERSION = "3.0"

BASE_URL = "https://api.india.delta.exchange/v2"

DELTA_API_KEY = os.getenv("DELTA_API_KEY")
DELTA_API_SECRET = os.getenv("DELTA_API_SECRET")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

DEFAULT_SYMBOL = "BTCUSD"
DEFAULT_TIMEFRAME = "5m"

SCAN_INTERVAL = 300

MIN_CONFIDENCE = 85
